#
#
#  The sequence of triangle numbers is generated by adding the natural numbers. So
# the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
# terms would be:
#
#     1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#     1: 1
#     3: 1,3
#     6: 1,2,3,6
#     10: 1,2,5,10
#     15: 1,3,5,15
#     21: 1,3,7,21
#     28: 1,2,4,7,14,28
#
#  We can see that 28 is the first triangle number
# to have over five divisors.
#
#  What is the value of the first triangle number
# to have over five hundred divisors?
#

require 'awesome_print'


def triangle_number (n)
  return n if n == 1
  return n + triangle_number(n-1)
end

10.times do |i|
  j = i+3
  cand = triangle_number j
  k = 2
  reduc = cand
  divis = []
  while k <= reduc do
    if (reduc%k) == 0
      divis << k
      reduc = reduc/k
      k = 2
    else
      k += 1
    end
  end
  ap cand
  ap divis
end


