


#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonaccis = [1, 2]

suma = 0

while (fibonaccis[-1] < 4000000) do
  suma = suma + fibonaccis[-1] if (fibonaccis[-1] % 2) == 0

  fibonaccis << fibonaccis[-1] + fibonaccis[-2]

  fibonaccis = fibonaccis[-2..-1]

end

puts suma


